import { prisma } from "@/lib/prisma";

// Generate daily report for a specific date
export async function generateDailyReport(date: Date = new Date()) {
  // Set to start and end of day
  const startOfDay = new Date(date);
  startOfDay.setHours(0, 0, 0, 0);
  
  const endOfDay = new Date(date);
  endOfDay.setHours(23, 59, 59, 999);
  
  console.log(`Generating report for ${startOfDay.toDateString()}...`);
  
  // Gather all metrics
  const metrics = await gatherMetrics(startOfDay, endOfDay);
  
  // Calculate conversion rates
  const conversionRates = calculateConversionRates(metrics);
  
  // Check if report already exists for this date
  const existingReport = await prisma.dailyReport.findUnique({
    where: { date: startOfDay },
  });
  
  // Prepare data with JSON stringification
  const reportData = {
    pageViews: metrics.pageViews,
    uniqueVisitors: metrics.uniqueVisitors,
    productViews: metrics.productViews,
    avgSessionDuration: metrics.avgSessionDuration,
    cartAdds: metrics.cartAdds,
    checkoutsStarted: metrics.checkoutsStarted,
    orders: metrics.orders,
    revenue: metrics.revenue,
    abandonedCarts: metrics.abandonedCarts,
    abandonedCartValue: metrics.abandonedCartValue,
    avgOrderValue: metrics.avgOrderValue,
    viewToCartRate: conversionRates.viewToCartRate,
    cartToCheckoutRate: conversionRates.cartToCheckoutRate,
    checkoutToOrderRate: conversionRates.checkoutToOrderRate,
    overallConversionRate: conversionRates.overallConversionRate,
    topViewedProducts: JSON.stringify(metrics.topViewedProducts),
    topSoldProducts: JSON.stringify(metrics.topSoldProducts),
    lowStockAlerts: JSON.stringify(metrics.lowStockAlerts),
    isAutoGenerated: true,
  };
  
  if (existingReport) {
    // Update existing report
    const updated = await prisma.dailyReport.update({
      where: { id: existingReport.id },
      data: reportData,
    });
    console.log(`Updated report for ${startOfDay.toDateString()}`);
    return updated;
  }
  
  // Create new report
  const report = await prisma.dailyReport.create({
    data: {
      date: startOfDay,
      ...reportData,
    },
  });
  
  console.log(`Created report for ${startOfDay.toDateString()}`);
  return report;
}

// Gather all metrics for the day
async function gatherMetrics(startOfDay: Date, endOfDay: Date) {
  // Traffic metrics from AnalyticsEvent
  const [
    pageViews,
    uniqueVisitors,
    productViews,
    cartAdds,
    checkoutsStarted,
  ] = await Promise.all([
    // Page views
    prisma.analyticsEvent.count({
      where: {
        type: "page_view",
        createdAt: { gte: startOfDay, lte: endOfDay },
      },
    }),
    // Unique visitors
    prisma.analyticsEvent.groupBy({
      by: ["sessionId"],
      where: {
        createdAt: { gte: startOfDay, lte: endOfDay },
      },
    }).then(sessions => sessions.length),
    // Product views
    prisma.analyticsEvent.count({
      where: {
        type: "product_view",
        createdAt: { gte: startOfDay, lte: endOfDay },
      },
    }),
    // Cart adds
    prisma.analyticsEvent.count({
      where: {
        type: "cart_add",
        createdAt: { gte: startOfDay, lte: endOfDay },
      },
    }),
    // Checkouts started
    prisma.analyticsEvent.count({
      where: {
        type: "checkout_start",
        createdAt: { gte: startOfDay, lte: endOfDay },
      },
    }),
  ]);
  
  // Orders and revenue
  const ordersToday = await prisma.order.findMany({
    where: {
      createdAt: { gte: startOfDay, lte: endOfDay },
      status: { not: "CANCELLED" },
    },
    select: {
      id: true,
      totalAmount: true,
      items: {
        select: {
          productId: true,
          productName: true,
          quantity: true,
        },
      },
    },
  });
  
  const orders = ordersToday.length;
  const revenue = ordersToday.reduce((sum, o) => sum + o.totalAmount, 0);
  const avgOrderValue = orders > 0 ? revenue / orders : 0;
  
  // Abandoned carts (sessions with cart_add but no order)
  const abandonedCartSessions = await prisma.cartEvent.findMany({
    where: {
      eventType: "add",
      createdAt: { gte: startOfDay, lte: endOfDay },
    },
    distinct: ["sessionId"],
    select: {
      sessionId: true,
    },
  });
  
  // Calculate abandoned carts (simplified)
  const completedSessionIds = new Set(
    ordersToday.map(() => `order_${Math.random()}`) // Placeholder
  );
  
  const abandonedCarts = Math.max(0, abandonedCartSessions.length - orders);
  const abandonedCartValue = abandonedCarts * avgOrderValue; // Estimate
  
  // Top viewed products
  const topViewed = await prisma.analyticsEvent.groupBy({
    by: ["productId"],
    where: {
      type: "product_view",
      createdAt: { gte: startOfDay, lte: endOfDay },
      productId: { not: null },
    },
    _count: { productId: true },
    orderBy: { _count: { productId: "desc" } },
    take: 5,
  });
  
  const topViewedProducts = await Promise.all(
    topViewed.map(async (item) => {
      const product = await prisma.product.findUnique({
        where: { id: item.productId! },
        select: { id: true, name: true },
      });
      return {
        id: product?.id || item.productId!,
        name: product?.name || "Unknown Product",
        views: item._count.productId,
      };
    })
  );
  
  // Top sold products
  const productSales: Record<string, { id: string; name: string; sales: number }> = {};
  ordersToday.forEach(order => {
    order.items.forEach(item => {
      if (!productSales[item.productId]) {
        productSales[item.productId] = {
          id: item.productId,
          name: item.productName,
          sales: 0,
        };
      }
      productSales[item.productId].sales += item.quantity;
    });
  });
  
  const topSoldProducts = Object.values(productSales)
    .sort((a, b) => b.sales - a.sales)
    .slice(0, 5);
  
  // Low stock alerts
  const lowStockProducts = await prisma.product.findMany({
    where: {
      status: "available",
      stockQuantity: { lte: 3 },
    },
    select: { id: true, name: true, stockQuantity: true },
    take: 10,
  });
  
  const lowStockAlerts = lowStockProducts.map(p => ({
    id: p.id,
    name: p.name,
    stock: p.stockQuantity,
  }));
  
  // Estimate average session duration (simplified)
  const avgSessionDuration = pageViews > 0 ? Math.round((uniqueVisitors / pageViews) * 120) : 0;
  
  return {
    pageViews,
    uniqueVisitors,
    productViews,
    avgSessionDuration,
    cartAdds,
    checkoutsStarted,
    orders,
    revenue,
    abandonedCarts,
    abandonedCartValue,
    avgOrderValue,
    topViewedProducts,
    topSoldProducts,
    lowStockAlerts,
  };
}

// Calculate conversion rates
function calculateConversionRates(metrics: any) {
  const viewToCartRate = metrics.productViews > 0 
    ? (metrics.cartAdds / metrics.productViews) * 100 
    : 0;
  
  const cartToCheckoutRate = metrics.cartAdds > 0 
    ? (metrics.checkoutsStarted / metrics.cartAdds) * 100 
    : 0;
  
  const checkoutToOrderRate = metrics.checkoutsStarted > 0 
    ? (metrics.orders / metrics.checkoutsStarted) * 100 
    : 0;
  
  const overallConversionRate = metrics.pageViews > 0 
    ? (metrics.orders / metrics.pageViews) * 100 
    : 0;
  
  return {
    viewToCartRate: Math.round(viewToCartRate * 100) / 100,
    cartToCheckoutRate: Math.round(cartToCheckoutRate * 100) / 100,
    checkoutToOrderRate: Math.round(checkoutToOrderRate * 100) / 100,
    overallConversionRate: Math.round(overallConversionRate * 100) / 100,
  };
}

// Generate AI summary for the report (placeholder - will be enhanced in Phase 3)
export async function generateReportSummary(report: any): Promise<string> {
  const parts: string[] = [];
  
  // Parse JSON fields
  const topViewed = JSON.parse(report.topViewedProducts || "[]");
  const lowStock = JSON.parse(report.lowStockAlerts || "[]");
  
  // Sales summary
  if (report.orders > 0) {
    parts.push(`Today you had ${report.orders} order${report.orders !== 1 ? 's' : ''} totaling ₹${report.revenue.toLocaleString()}.`);
  } else {
    parts.push("No orders today.");
  }
  
  // Traffic
  parts.push(`${report.uniqueVisitors} unique visitors browsed your store.`);
  
  // Top product
  if (topViewed.length > 0) {
    parts.push(`Most viewed: ${topViewed[0].name} (${topViewed[0].views} views).`);
  }
  
  // Low stock warning
  if (lowStock.length > 0) {
    parts.push(`⚠️ ${lowStock.length} product${lowStock.length !== 1 ? 's are' : ' is'} running low on stock.`);
  }
  
  return parts.join(" ");
}

// Get report for specific date
export async function getDailyReport(date: Date) {
  const startOfDay = new Date(date);
  startOfDay.setHours(0, 0, 0, 0);
  
  return prisma.dailyReport.findUnique({
    where: { date: startOfDay },
  });
}

// Get reports for date range
export async function getReportsInRange(startDate: Date, endDate: Date) {
  return prisma.dailyReport.findMany({
    where: {
      date: {
        gte: startDate,
        lte: endDate,
      },
    },
    orderBy: { date: "desc" },
  });
}

// Get latest report
export async function getLatestReport() {
  return prisma.dailyReport.findFirst({
    orderBy: { date: "desc" },
  });
}
